export const BadWords = [
    // Malas palabras
    "cabrón", "hijo de puta", "pendejo", "gilipollas", "maldición",
    "coño", "puta", "maricón", "zorra", "mierda", "chingar",
    "joder", "pendeja", "imbécil", "asqueroso", "picha",
    "huevón", "follador", "güey", "cuca", "boyo", "bollo", "cagón",
    "mamón", "pelotudo", "carajo", "pendejear", "estúpido", "peludo",
    "pelua", "peluda", "voyo", "vollo", "nepe", "totaila", "cucaila",
    "singao", "singar", "singada", "singado",
    "tarado", "polla", "hijueputa", "coñazo", "cagada",
    "pendejito", "marica", "bicho", "pendejismo", "reverendo",
    "gay", "gayy", "gayyy", "gayyyyy", "gaypvto", "pvto", "patan", "patán", "gey",
    "chupapijas", "desgraciado", "hijaputa", "mamonazo",
    "follón", "putón", "picha", "cojones", "chingar",
    "follar", "putear", "cogerse", "follando", "mamar",
    "chocho", "mariconada", "mardito", "putísima", "culero",
    "pendejear", "cabrón", "hijueputa", "cagón", "pendejo",
    "mamonazo", "pendejo", "pendejismo", "morrón", "cagón",
    "soplapollas", "cabrón", "hijaputa", "pendejo", "güey",
    "maricón", "pendejear", "desgraciado", "pichón", "pija",
    "pendejo", "picha", "putón", "follador", "güey",
    "pendejazo", "pichón", "cagón", "hijueputa", "mariconazo",
    "pendejear", "cabrón", "cogido", "cogida", "pendejo",
    "güey", "putón", "cabrón", "culón", "follador",
    "pichón", "desgraciado", "güey", "picha", "pendejismo",
    "desgraciado", "hijaputa", "mamonazo", "pendejo",
    "sopla", "pendejear", "cagón", "hijoputa", "maricon",
    "hijueputa", "pendejo", "culero", "cagón",
    "pendejear", "güey", "picha", "follador", "cojones",
    "putón", "pendejo", "hijaputa", "cabrón", "picha",
    "pendejear", "pendejos", "pendejismo", "coño", "putón",
    "hijueputa", "follador", "cabrones", "güey", "pendejo",
    "cagarse", "desgraciado", "mamarracho", "sinvergüenza", "pendejear",
    "pichón", "follón", "cabrón", "cogida", "maricón",
    "pendejo", "folladora", "cogerse", "picha", "coñazo",
    "pendejismo", "hijueputa", "hijaputa", "putón", "güey",
    "culero", "cogido", "pendejazo", "follador", "hijoputa",
    "mariconada", "pendejear", "picha", "morrón", "mamonazo",
    "carajo", "cojones", "pendejito", "marica", "tarado",
    "estúpido", "imbeciloides", "asqueroso", "huevón", "chupapijas",
    "zorra", "desgraciado", "putísima", "follando", "soplapollas",
    "cagón", "maricón", "putear", "follar", "chocha", "marika", "mariquita",
    "marikita", "pinga", "pingon", "palón", "palon", "pingón",
    "comemierda", "come mierda", "come pinga", "comepinga",
    "joder", "sexo", "sexualidad", "bastardo", "tarugo", "inútil", "vago", "holgazán",
    "gusano", "desalmado", "cara de perro", "patán", "chismoso", "llorón", "soplón",
    "baboso", "cachetón", "miedoso", "felón", "haragán", "granuja", "mojigato",
    "simplón", "mugriento", "metiche", "zalamero", "canalla", "manganzón", "piltrafa",
    "simplote", "tramposo", "pelele", "narizón", "papanatas", "cabeza hueca", "pelafustán",
    "bocón", "sarnoso", "patudo", "espantapájaros", "bobalicón", "simplón", "tarado",
    "soquete", "chupamedias", "cagueta", "tontorrón", "mordaz", "lamebotas", "caradura",
    "cretino", "necio", "idiota", "tonto", "zafio", "patético", "despreciable", "mediocre",
    "estirado", "ridículo", "cursi", "pedante", "mezquino", "ruin", "rastrero", "miserable",
    "malhablado", "desgraciao", "infeliz", "pasmado", "perdedor", "pasmón", "tacaño", "engreído",
    "afeminado", "retardado", "lerdo", "botarate", "gordinflón", "lameculos",
    "pornografía", "pornográfico", "erótico", "orgasmo", "sexo", "sexualidad", "masturbación",
    "penetración", "prostitución", "desnudo", "desnudez", "clítoris", "vagina", "pene", "testículos",
    "genitales", "coito", "eyaculación", "erección", "frotación", "menstruación", "porn", "porno", "condón",
    "anticonceptivo", "sexo oral", "sexo anal", "fetiche", "sadomasoquismo", "bdsm", "sado", "voyeurismo",
    "exhibicionismo", "travestismo", "orgía", "swinger", "lubricante", "dildo", "vibrador", "juguete sexual",
    "pornhub", "onlyfans", "camgirl", "camshow", "escort", "striptease", "desnudista", "desvestirse", "pechos",
    "senos", "tetas", "nalgas", "culo", "trasero", "lencería", "bragas", "tanga", "topless", "mamario", "caricias",
    "sexo explícito", "hardcore", "softcore", "amateur", "bdsm", "sexo grupal", "semen", "virgen", "desvirgar",
    "himen", "orgásmico", "erotismo", "libido", "sensual", "prostituta", "prostituto", "gigoló", "ninfómana",
    "pornstar", "desviación sexual", "fantasía sexual", "heterosexual", "homosexual", "bisexual", "pansexual",
    "asexual", "demisexual", "sapiosexual", "transgénero", "transexual", "cisgénero", "intersexual", "hermafrodita",
    "no binario", "queer", "drag queen", "drag king", "crossdresser", "andrógeno",
    "homofobia", "racismo", "xenofobia", "machismo", "sexismo",
    "misoginia", "misantrópico", "clasismo", "discriminación", "prejuicio",
    "odio", "intolerancia", "fanatismo", "supremacía", "segregación",
    "genocidio", "fobia", "islamofobia", "cristianofobia", "antisemitismo",
    "abusador", "acosador", "hostigador", "matón", "terrorista",
    "opresor", "marginador", "exclusión", "subyugador", "explotador",
    "violencia", "crueldad", "agresividad", "odio racial", "odio religioso",
    "deshumanización", "inhumano", "degradante", "ofensivo", "vejatorio",
    "abusivo", "hostil", "sectarismo", "autoritarismo", "supremacista",
    "vejestorio", "vejete", "hijoeputa", "hijoeputo", "hijueputa", "hijueputo",
    "hdp", "hijueputa", "hijueputo", "hijoputa", "hijoputo", "hijodeputa",
    "odio", "asco", "repulsión", "repugnancia", "aversión",
    "desprecio", "desdén", "hostilidad", "crueldad", "intolerancia",
    "resentimiento", "envidia", "rencor", "antipatía", "coraje",
    "inhumanidad", "brutalidad", "violencia", "toxicidad", "arrogancia",
    "soberbia", "egoísmo", "traición", "perversión", "maldad",
    "degradación", "vejación", "burla", "humillación", "menosprecio",
    "ridiculización", "exclusión", "marginación", "abusador", "acosador",
    "agresor", "infamia", "deshonra", "indignidad", "corrupción",
    "hipocresía", "falsedad", "engaño", "estafa", "manipulación",
    "mentira", "crueldad", "brutalidad", "abuso", "desalmado",
    "indiferencia", "apatía", "cinismo", "sarcasmo", "insensibilidad",
    "deshumanización", "inhumano", "malicioso", "malintencionado", "retorcido",
    "repugnante", "detestable", "desagradable", "miserable", "ruin",
    "mezquino", "odioso", "tóxico", "turbio", "perverso",
    "siniestro", "malvado", "nauseabundo", "despreciable", "vil",
    "escoria", "basura", "parásito", "sanguijuela", "despojo",
    "asquerosisimo", "asquerosísimo", "repugnante", "repelente", "repulsivo", "repugnoso",
    "Eso entra con fuerza", "Lo tienes bien duro", "Mételo más adentro", "Ya se está mojando",
    "No puedo con tanto", "Me gusta cómo lo mueves", "Aprieta más fuerte", "Dale hasta que termine",
    "Esto no cabe aquí", "Cógelo con las dos manos", "Se siente rico así",
    "Está más grande de lo que esperaba", "Me vas a hacer gritar", "¡Qué rico está esto!", "Voy a explotar",
    "Ponlo donde te guste más", "Está tan caliente que no aguanto", "Muévelo despacito primero",
    "Eso me lo como todo", "Dámelo completo", "Te quedó bien apretado", "No pares, sigue así",
    "Eso está muy resbaloso", "Se siente mejor si lo haces despacio", "violar", "Ahh~", "Ah~", "Ahhh~", "Ahhhn~",
    "Ahh", "Ah", "Ahhh", "Ahhhn", "Ahhhh", "Ahhhhn", "Ahhhhh", "Ahhhhhn", "Ahhhhhh", "Ahhhhhhn", "Ahhhhhhh",
    "no servir para nada", "no valer para nada", "no valer un pimiento", "no valer un comino", "no valer un carajo",
    "no sirve para nada", "no sirvió para nada", "no sirvio para nada", "manco", "manca", "mancazo", "mancaza",
    "imbécil", "imbecil", "imbeciles", "imbéciles", "idiota", "idiotas", "tonto", "tonta", "tontos", "tontas",
    "zorra", "zorras", "pvta", "pvtas", "muere", "muerete", "nerd", "friki", "anormal", "creido", "creida",
    "creída", "creído", "malnacido", "malnacida", "malparido", "malparida", "chupahuevo", "chupaguevo",
    "mamaguevo", "chupahuebo", "chupaguebo", "mamaguebo", "mamahuevo", "mamahuebo", "crica", "cricka",
    "crika",


    // Palabras relacionadas con política
    "dictadura", "corrupto", "golpe de estado", "populismo",
    "neoliberalismo", "extremismo", "fascismo", "totalitarismo",
    "demagogia", "clientelismo", "politicucho", "partidismo",
    "tiranía", "anarquía", "censura", "protesta", "manifestación",
    "opresión", "desigualdad", "revolución", "anarquismo",
    "progresismo", "conservadurismo", "radicalismo", "crisis",
    "autoritarismo", "descontento", "lobby", "plebiscito",
    "voto nulo", "fraude electoral", "manipulación", "desobediencia",

    // Palabras relacionadas con religión
    "herejía", "blasfemia", "secta", "fanatismo",
    "fundamentalismo", "idolatría", "ateo", "agnóstico",
    "misticismo", "religión", "dogma", "sacrilegio",
    "sincretismo", "paganismo", "teocracia", "cruzada",
    "inquisición", "santo", "pecado", "redentor", "apóstata",
    "evangelio", "profeta", "ritual", "doctrina", "creencia",
    "adoración", "sacerdote", "abad", "monje", "abadesa",
    "catedral", "capilla", "templo", "altar", "sacrificio",
    "culto", "devoción", "peregrinación", "pagano", "divinidad",
    "confesión", "penitencia", "exorcismo", "sermón", "comulgante",
    "apóstol", "mesías", "liturgia", "cielo", "infierno",
    "parábola", "idolatrar", "santos", "crucifijo", "ángel",
    "redención", "diablo", "tentación", "sacramental", "abjuración",
    "antipapa", "bautismo", "eucaristía", "genuflexión", "iconoclastia",
    "martirio", "milagro", "profecía", "reliquia", "hereje",
    "sanctus", "teología", "transubstanciación", "vicario", "legado",
    "iglesia", "testigo de Jehová", "Jehová", "cristianismo", "catolicismo",
    "Dios", "Nuestro Señor", "Salvador", "el papa", "apocalipsis", 
    "destrucción", "tensión religiosa", "división", "intolerancia", "persecución",
    "redención", "iluminación", "ángeles caídos", "proselitismo", "purgatorio",
    "reencarnación", "profetizar", "ortodoxia", "salvación", "excomunión",
    "guerra santa", "conversión", "fe ciega", "alabanza", "pecador",
    "veneración", "converso", "sacerdocio", "teocracia", "precepto",
    "ayuno", "meditación", "buda", "karma", "samsara",
    "adorador", "pantheón", "misa", "oración", "crucifixión",
    "desamparado", "propósito divino", "satanismo", "blasfemo", "cosmogonía",
    "sectario", "herejía", "temor", "demonio",

];
